"use server";

import { revalidatePath } from "next/cache";
import { currentUser, requireFounderForAction } from "@/lib/auth";
import { FOUNDER } from "@/lib/founder";
import { findClerkUserByEmail } from "@/lib/admin-analytics/clerk-users";
import { createPostgresLeadRepositories } from "@/lib/leads/db/postgres-repository";
import { getEmployeeHistoryPage, returnOpenLeadsToFounder } from "@/lib/leads/employee-profile";
import { createPostgresStaffRepository } from "@/lib/staff/db/postgres-repository";
import { StaffNotFoundError, StaffStateError, StaffValidationError } from "@/lib/staff/errors";
import { approveStaffMember, changeStaffEmail, enrollFounderAsEmployee, exitStaffMember, inviteStaffMember, setStaffActive } from "@/lib/staff/staff-service";
import type { ExitReason, StaffRole } from "@/lib/staff/types";
import type { LeadActor } from "@/lib/leads/types";

/**
 * Founder-only team management. Every function calls requireFounderForAction FIRST (a Server Action is its own
 * network-callable endpoint); the staff service then refuses any non-FOUNDER actor a second time. People are invited by
 * the exact email they will sign in with; if an account with that email already exists its Clerk id is resolved here
 * on the server, and it is never typed or supplied by the browser. Nobody is ever deleted: they exit, and everything they
 * did stays. The employee ID is generated by the database and cannot be supplied or changed through any action here.
 */

export type StaffActionResult = { ok: true; message?: string } | { ok: false; error: string };

const GENERIC_ERROR = "Something went wrong. Please try again.";

function toResult(error: unknown): StaffActionResult {
  if (error instanceof StaffValidationError || error instanceof StaffStateError) return { ok: false, error: error.message };
  if (error instanceof StaffNotFoundError) return { ok: false, error: "That team member could not be found." };
  return { ok: false, error: GENERIC_ERROR };
}

/** Invites a person (they have no access until you approve them and they sign in with that email). */
export async function addStaffMemberAction(email: string, displayName: string, role: StaffRole = "EMPLOYEE"): Promise<StaffActionResult> {
  const founderId = await requireFounderForAction();
  const actor: LeadActor = { actorType: "FOUNDER", actorId: founderId };
  try {
    // An existing account with this email is linked now (still unapproved); otherwise the first sign-in links it. A lookup
    // failure is not an error: the invite works either way.
    const clerkUser = typeof email === "string" ? await findClerkUserByEmail(email).catch(() => null) : null;
    const member = await inviteStaffMember(createPostgresStaffRepository(), { displayName, email, role, userId: clerkUser?.id ?? null }, actor);
    revalidatePath("/admin/staff");
    return { ok: true, message: `${member.employeeId} created. They cannot sign in to the team area until you approve them.` };
  } catch (error) {
    return toResult(error);
  }
}

export async function approveStaffMemberAction(staffId: string): Promise<StaffActionResult> {
  const founderId = await requireFounderForAction();
  try {
    const member = await approveStaffMember(createPostgresStaffRepository(), staffId, { actorType: "FOUNDER", actorId: founderId });
    revalidatePath("/admin/staff");
    revalidatePath(`/admin/staff/${member.employeeId}`);
    return { ok: true, message: member.status === "ACTIVE" ? `${member.employeeId} is approved and active.` : `${member.employeeId} is approved. They get access the first time they sign in with ${member.email}.` };
  } catch (error) {
    return toResult(error);
  }
}

export async function setStaffActiveAction(staffId: string, active: boolean): Promise<StaffActionResult> {
  const founderId = await requireFounderForAction();
  const actor: LeadActor = { actorType: "FOUNDER", actorId: founderId };
  try {
    const member = await setStaffActive(createPostgresStaffRepository(), staffId, active, actor);
    revalidatePath(`/admin/staff/${member.employeeId}`);
  } catch (error) {
    return toResult(error);
  }
  revalidatePath("/admin/staff");
  revalidatePath("/admin/leads");
  return { ok: true };
}

/** Changes the approved login email. The employee ID, ownership and history never change; old and new address are logged. */
export async function changeStaffEmailAction(staffId: string, newEmail: string): Promise<StaffActionResult> {
  const founderId = await requireFounderForAction();
  try {
    const member = await changeStaffEmail(createPostgresStaffRepository(), staffId, newEmail, { actorType: "FOUNDER", actorId: founderId });
    revalidatePath("/admin/staff");
    revalidatePath(`/admin/staff/${member.employeeId}`);
    return { ok: true, message: `${member.employeeId}'s login email is now ${member.email}.` };
  } catch (error) {
    return toResult(error);
  }
}

/** Records that a person has left. Ends their access and keeps every record. */
export async function exitStaffMemberAction(staffId: string, reason: ExitReason): Promise<StaffActionResult> {
  const founderId = await requireFounderForAction();
  try {
    const member = await exitStaffMember(createPostgresStaffRepository(), staffId, reason, { actorType: "FOUNDER", actorId: founderId });
    revalidatePath("/admin/staff");
    revalidatePath(`/admin/staff/${member.employeeId}`);
    revalidatePath("/admin/leads");
    return { ok: true, message: `${member.employeeId} has exited. Their access is removed and their history is kept.` };
  } catch (error) {
    return toResult(error);
  }
}

/** Returns every open lead a person still owns to the Founder queue (history is kept; each return is an event). */
export async function returnOpenLeadsAction(employeeId: string): Promise<StaffActionResult> {
  const founderId = await requireFounderForAction();
  try {
    const { returned, remaining } = await returnOpenLeadsToFounder(createPostgresLeadRepositories(), createPostgresStaffRepository(), { actorType: "FOUNDER", actorId: founderId }, employeeId);
    revalidatePath("/admin/staff");
    revalidatePath("/admin/leads");
    return { ok: true, message: returned === 0 ? "They have no leads to return." : `${returned} lead${returned === 1 ? "" : "s"} returned to your queue${remaining > 0 ? `; ${remaining} remain (run it again)` : ""}.` };
  } catch (error) {
    return toResult(error);
  }
}

export interface HistoryRow {
  id: string;
  leadId: string;
  eventType: string;
  at: string;
}

/** The next page of what a person did (Founder only). */
export async function loadEmployeeHistoryAction(employeeId: string, beforeIso: string): Promise<{ ok: true; rows: HistoryRow[] } | { ok: false; error: string }> {
  const founderId = await requireFounderForAction();
  const before = new Date(beforeIso);
  if (Number.isNaN(before.getTime())) return { ok: false, error: "That page could not be loaded." };
  try {
    const events = await getEmployeeHistoryPage(createPostgresLeadRepositories(), createPostgresStaffRepository(), { actorType: "FOUNDER", actorId: founderId }, employeeId, before);
    return { ok: true, rows: events.map((e) => ({ id: e.id, leadId: e.leadId, eventType: e.eventType, at: e.createdAt.toISOString() })) };
  } catch {
    return { ok: false, error: GENERIC_ERROR };
  }
}

/** The Founder enrols themselves as the first team member, so their own calls and leads run through the team workspace and are tracked like anyone's. */
export async function enableMyWorkspaceAction(): Promise<StaffActionResult> {
  const founderId = await requireFounderForAction();
  try {
    const user = await currentUser();
    const verified = user?.emailAddresses.find((e) => e.verification?.status === "verified")?.emailAddress ?? null;
    // The team record carries the Founder's name as the public site states it, not whatever the sign-in account happens to be called.
    const name = FOUNDER.name;
    const { member, created } = await enrollFounderAsEmployee(createPostgresStaffRepository(), { userId: founderId, displayName: name, email: verified });
    revalidatePath("/admin/staff");
    return { ok: true, message: created ? `Your calling workspace is ready (${member.employeeId}).` : `Your calling workspace is already set up (${member.employeeId}).` };
  } catch (error) {
    return toResult(error);
  }
}
